/* eslint-disable no-unused-vars */
const REFERENCE_URL = 'https://harshita1262.github.io/memory-management-simulator/';

const CURRENT = {
  pageBackground: '#36393f',
  pageWindowGap: 8,
  pageShadowColor: '#000000',
  pageShadowRadius: 12,
  pageText: '#dcddde',
  globalTextDefault: '#ffffff',
  chatContainerBackground: '#000000',
  bannerErrorBackground: '#b43a3a',
  bannerErrorText: '#ffcac8',
  bannerSuccessBackground: '#59c82d',
  bannerSuccessText: '#ffffff',
  headerBackground: '#202225',
  headerText: '#ffffff',
  headerIconColor: '#dcddde',
  headerIconHoverColor: '#00eb00',
  sidebarToggleColor: '#ffffff',
  headerTitleGlowBase: '#ffffff',
  headerTitleGlowFromAccent: '#d13737',
  headerTitleGlowToAccent: '#00eb00',
  sidebarBackground: '#2f3136',
  sidebarText: '#ffffff',
  sidebarSectionLabel: '#ffffff',
  sidebarRoomPillBackground: '#000000',
  sidebarRoomPillBackgroundOpacity: 0.1,
  sidebarUserDefault: '#ffffff',
  sidebarCurrentUser: '#00eb00',
  sidebarCloseIconColor: '#dcddde',
  sidebarOverlayScrim: '#000000',
  sidebarOverlayScrimOpacity: 0.5,
  chatPanelBackground: '#000000',
  historySeparatorText: '#72767d',
  historySeparatorBorder: '#40444b',
  messageBubbleBackground: '#000000',
  messageBubbleBorder: '#e0e0e0',
  metaBaseColor: '#e4e4e4',
  metaOpacity: 0.7,
  metaNameColor: '#885858',
  metaTimeColor: '#885858',
  messageBodyText: '#ffffff',
  codeBlockBackground: '#202225',
  codeBlockBorder: '#e0e0e0',
  inlineCodeColor: '#00eb00',
  mentionColor: '#00eb00',
  typingIndicatorColor: '#72767d',
  scrollButtonBackground: '#202225',
  scrollButtonHoverBackground: '#2f3136',
  scrollButtonBorder: '#e0e0e0',
  scrollButtonIconColor: '#00eb00',
  unreadBadgeBackground: '#b43a3a',
  unreadBadgeText: '#ffcac8',
  formBackground: '#202225',
  inputBackground: '#000000',
  inputText: '#ffffff',
  inputPlaceholder: '#72767d',
  sendButtonBackground: '#2261aa',
  sendButtonText: '#d2e4ff',
  sendButtonHoverBackground: '#1567ff',
  leaveButtonBackground: '#b43a3a',
  leaveButtonText: '#ffcac8',
  leaveButtonHoverBackground: '#ff1d15',
};

const DEEP_PURPLE = {
  pageBackground: '#130425',
  pageWindowGap: 64,
  pageShadowColor: '#000000',
  pageShadowRadius: 48,
  pageText: '#ffffff',
  globalTextDefault: '#ffffff',
  chatContainerBackground: '#090514',
  bannerErrorBackground: '#2d0f2f',
  bannerErrorText: '#ef4444',
  bannerSuccessBackground: '#0f2d1a',
  bannerSuccessText: '#22c55e',
  headerBackground: '#1a1330',
  headerText: '#e6e6e6',
  headerIconColor: '#9580b8',
  headerIconHoverColor: '#a855f7',
  sidebarToggleColor: '#ffffff',
  headerTitleGlowBase: '#ffffff',
  headerTitleGlowFromAccent: '#ffae00',
  headerTitleGlowToAccent: '#0400ff',
  sidebarBackground: '#120623',
  sidebarText: '#e8e8e8',
  sidebarSectionLabel: '#ffffff',
  sidebarRoomPillBackground: '#2a1550',
  sidebarRoomPillBackgroundOpacity: 0.6,
  sidebarUserDefault: '#e8e8e8',
  sidebarCurrentUser: '#22c55e',
  sidebarCloseIconColor: '#9580b8',
  sidebarOverlayScrim: '#050000',
  sidebarOverlayScrimOpacity: 0.2,
  chatPanelBackground: '#0d041b',
  historySeparatorText: '#9580b8',
  historySeparatorBorder: '#7f6fb8',
  messageBubbleBackground: '#1a1330',
  messageBubbleBorder: '#544285',
  metaBaseColor: '#e8e8e8',
  metaOpacity: 1,
  metaNameColor: '#981aff',
  metaTimeColor: '#a380f4',
  messageBodyText: '#ffffff',
  codeBlockBackground: '#150d21',
  codeBlockBorder: '#1a092a',
  inlineCodeColor: '#ffae00',
  mentionColor: '#00db50',
  typingIndicatorColor: '#9580b8',
  scrollButtonBackground: '#180d3b',
  scrollButtonHoverBackground: '#32116e',
  scrollButtonBorder: '#3b2d6e',
  scrollButtonIconColor: '#bc75ff',
  unreadBadgeBackground: '#ff3d3d',
  unreadBadgeText: '#ffffff',
  formBackground: '#1a0b37',
  inputBackground: '#0e0717',
  inputText: '#f1efef',
  inputPlaceholder: '#9d82c9',
  sendButtonBackground: '#470d7d',
  sendButtonText: '#ffffff',
  sendButtonHoverBackground: '#3100a3',
  leaveButtonBackground: '#5000b3',
  leaveButtonText: '#ffffff',
  leaveButtonHoverBackground: '#d01616',
};

const TOKEN_GROUPS = [
  {
    id: 'pageShell',
    label: 'Page shell',
    tokens: [
      { key: 'pageBackground', label: 'Page background', cssSelector: 'body.chat-page / preview surround', type: 'color' },
      { key: 'pageWindowGap', label: 'Gap around chat window', cssSelector: '.lab-preview-scroll padding', type: 'length', min: 4, max: 64, step: 1, unit: 'px' },
      { key: 'pageShadowColor', label: 'Chat window shadow color', cssSelector: '.chat-mock box-shadow', type: 'color' },
      { key: 'pageShadowRadius', label: 'Chat window shadow radius', cssSelector: '.chat-mock box-shadow blur', type: 'length', min: 0, max: 64, step: 1, unit: 'px' },
      { key: 'pageText', label: 'Page text', cssSelector: 'body', type: 'color' },
      { key: 'globalTextDefault', label: 'Global text default', cssSelector: '*', type: 'color' },
      { key: 'chatContainerBackground', label: 'Chat container background', cssSelector: '.chat-container', type: 'color' },
    ],
  },
  {
    id: 'connectionBanner',
    label: 'Connection banner',
    tokens: [
      { key: 'bannerErrorBackground', label: 'Error banner background', cssSelector: '.connection-banner--error', type: 'color' },
      { key: 'bannerErrorText', label: 'Error banner text', cssSelector: '.connection-banner--error', type: 'color' },
      { key: 'bannerSuccessBackground', label: 'Success banner background', cssSelector: '.connection-banner--success', type: 'color' },
      { key: 'bannerSuccessText', label: 'Success banner text', cssSelector: '.connection-banner--success', type: 'color' },
    ],
  },
  {
    id: 'header',
    label: 'Header',
    tokens: [
      { key: 'headerBackground', label: 'Header background', cssSelector: '.chat-header', type: 'color' },
      { key: 'headerText', label: 'Header text', cssSelector: '.chat-header', type: 'color' },
      { key: 'headerIconColor', label: 'Header icon color', cssSelector: '.btn-icon', type: 'color' },
      { key: 'headerIconHoverColor', label: 'Header icon hover', cssSelector: '.btn-icon:hover', type: 'color' },
      { key: 'sidebarToggleColor', label: 'Sidebar toggle color', cssSelector: '.sidebar-toggle', type: 'color' },
      { key: 'headerTitleGlowBase', label: 'Title glow base', cssSelector: '.glow', type: 'color' },
      { key: 'headerTitleGlowFromAccent', label: 'Title glow from accent', cssSelector: '@keyframes glow from', type: 'color' },
      { key: 'headerTitleGlowToAccent', label: 'Title glow to accent', cssSelector: '@keyframes glow to', type: 'color' },
    ],
  },
  {
    id: 'sidebar',
    label: 'Sidebar',
    tokens: [
      { key: 'sidebarBackground', label: 'Sidebar background', cssSelector: '.chat-sidebar', type: 'color' },
      { key: 'sidebarText', label: 'Sidebar text', cssSelector: '.chat-sidebar', type: 'color' },
      { key: 'sidebarSectionLabel', label: 'Section labels', cssSelector: '.chat-sidebar h3', type: 'color' },
      { key: 'sidebarRoomPillBackground', label: 'Room pill background', cssSelector: '.chat-sidebar h2', type: 'color' },
      { key: 'sidebarRoomPillBackgroundOpacity', label: 'Room pill opacity', cssSelector: '.chat-sidebar h2', type: 'opacity', min: 0, max: 1, step: 0.05 },
      { key: 'sidebarUserDefault', label: 'Default user color', cssSelector: '.chat-sidebar ul li', type: 'color' },
      { key: 'sidebarCurrentUser', label: 'Current user highlight', cssSelector: '.curr-user', type: 'color' },
      { key: 'sidebarCloseIconColor', label: 'Close icon color', cssSelector: '.sidebar-close', type: 'color' },
      { key: 'sidebarOverlayScrim', label: 'Overlay scrim color', cssSelector: 'body.sidebar-open::after', type: 'color' },
      { key: 'sidebarOverlayScrimOpacity', label: 'Overlay scrim opacity', cssSelector: 'body.sidebar-open::after', type: 'opacity', min: 0, max: 1, step: 0.05 },
    ],
  },
  {
    id: 'chatPanel',
    label: 'Chat panel & history',
    tokens: [
      { key: 'chatPanelBackground', label: 'Chat panel background', cssSelector: '.chat-panel', type: 'color' },
      { key: 'historySeparatorText', label: 'History separator text', cssSelector: '.history-separator', type: 'color' },
      { key: 'historySeparatorBorder', label: 'History separator border', cssSelector: '.history-separator', type: 'color' },
    ],
  },
  {
    id: 'messageBubbles',
    label: 'Message bubbles & metadata',
    tokens: [
      { key: 'messageBubbleBackground', label: 'Bubble background', cssSelector: '.message', type: 'color' },
      { key: 'messageBubbleBorder', label: 'Bubble border', cssSelector: '.message', type: 'color' },
      { key: 'metaBaseColor', label: 'Meta row base color', cssSelector: '.message .meta', type: 'color' },
      { key: 'metaOpacity', label: 'Meta row opacity', cssSelector: '.message .meta', type: 'opacity', min: 0.4, max: 1, step: 0.05 },
      { key: 'metaNameColor', label: 'Username color', cssSelector: '.meta-name', type: 'color' },
      { key: 'metaTimeColor', label: 'Timestamp color', cssSelector: '.meta-time', type: 'color' },
      { key: 'messageBodyText', label: 'Message body text', cssSelector: '.message .text', type: 'color' },
    ],
  },
  {
    id: 'richContent',
    label: 'Rich message content',
    tokens: [
      { key: 'codeBlockBackground', label: 'Code block background', cssSelector: '.message .text pre', type: 'color' },
      { key: 'codeBlockBorder', label: 'Code block border', cssSelector: '.message .text pre', type: 'color' },
      { key: 'inlineCodeColor', label: 'Inline code color', cssSelector: '.message .text code', type: 'color' },
      { key: 'mentionColor', label: 'Mention color', cssSelector: '.mention', type: 'color' },
    ],
  },
  {
    id: 'typingScroll',
    label: 'Typing & scroll FAB',
    tokens: [
      { key: 'typingIndicatorColor', label: 'Typing indicator', cssSelector: '.typing-indicator', type: 'color' },
      { key: 'scrollButtonBackground', label: 'Scroll button background', cssSelector: '.scroll-bottom', type: 'color' },
      { key: 'scrollButtonHoverBackground', label: 'Scroll button hover', cssSelector: '.scroll-bottom:hover', type: 'color' },
      { key: 'scrollButtonBorder', label: 'Scroll button border', cssSelector: '.scroll-bottom', type: 'color' },
      { key: 'scrollButtonIconColor', label: 'Scroll button icon', cssSelector: '.scroll-bottom', type: 'color' },
      { key: 'unreadBadgeBackground', label: 'Unread badge background', cssSelector: '.unread-badge', type: 'color' },
      { key: 'unreadBadgeText', label: 'Unread badge text', cssSelector: '.unread-badge', type: 'color' },
    ],
  },
  {
    id: 'messageInput',
    label: 'Message input footer',
    tokens: [
      { key: 'formBackground', label: 'Form footer background', cssSelector: '.chat-form-container', type: 'color' },
      { key: 'inputBackground', label: 'Input background', cssSelector: '.chat-form-container input', type: 'color' },
      { key: 'inputText', label: 'Input text', cssSelector: '.chat-form-container input', type: 'color' },
      { key: 'inputPlaceholder', label: 'Input placeholder', cssSelector: '::placeholder', type: 'color' },
    ],
  },
  {
    id: 'sendButton',
    label: 'Send button',
    tokens: [
      { key: 'sendButtonBackground', label: 'Send button background', cssSelector: '.send-btn', type: 'color' },
      { key: 'sendButtonText', label: 'Send button text', cssSelector: '.send-btn', type: 'color' },
      { key: 'sendButtonHoverBackground', label: 'Send button hover', cssSelector: '.send-btn:hover', type: 'color' },
    ],
  },
  {
    id: 'leaveButton',
    label: 'Leave room button',
    tokens: [
      { key: 'leaveButtonBackground', label: 'Leave button background', cssSelector: '.leave-room', type: 'color' },
      { key: 'leaveButtonText', label: 'Leave button text', cssSelector: '.leave-room', type: 'color' },
      { key: 'leaveButtonHoverBackground', label: 'Leave button hover', cssSelector: '.leave-room:hover', type: 'color' },
    ],
  },
];

const CSS_VAR_MAP = {
  pageBackground: '--page-background',
  pageWindowGap: '--page-window-gap',
  pageShadowColor: '--page-shadow-color',
  pageShadowRadius: '--page-shadow-radius',
  pageText: '--page-text',
  globalTextDefault: '--global-text-default',
  chatContainerBackground: '--chat-container-background',
  bannerErrorBackground: '--banner-error-background',
  bannerErrorText: '--banner-error-text',
  bannerSuccessBackground: '--banner-success-background',
  bannerSuccessText: '--banner-success-text',
  headerBackground: '--header-background',
  headerText: '--header-text',
  headerIconColor: '--header-icon-color',
  headerIconHoverColor: '--header-icon-hover-color',
  sidebarToggleColor: '--sidebar-toggle-color',
  headerTitleGlowBase: '--header-title-glow-base',
  headerTitleGlowFromAccent: '--header-title-glow-from-accent',
  headerTitleGlowToAccent: '--header-title-glow-to-accent',
  sidebarBackground: '--sidebar-background',
  sidebarText: '--sidebar-text',
  sidebarSectionLabel: '--sidebar-section-label',
  sidebarRoomPillBackground: '--sidebar-room-pill-background',
  sidebarRoomPillBackgroundOpacity: '--sidebar-room-pill-background-opacity',
  sidebarUserDefault: '--sidebar-user-default',
  sidebarCurrentUser: '--sidebar-current-user',
  sidebarCloseIconColor: '--sidebar-close-icon-color',
  sidebarOverlayScrim: '--sidebar-overlay-scrim',
  sidebarOverlayScrimOpacity: '--sidebar-overlay-scrim-opacity',
  chatPanelBackground: '--chat-panel-background',
  historySeparatorText: '--history-separator-text',
  historySeparatorBorder: '--history-separator-border',
  messageBubbleBackground: '--message-bubble-background',
  messageBubbleBorder: '--message-bubble-border',
  metaBaseColor: '--meta-base-color',
  metaOpacity: '--meta-opacity',
  metaNameColor: '--meta-name-color',
  metaTimeColor: '--meta-time-color',
  messageBodyText: '--message-body-text',
  codeBlockBackground: '--code-block-background',
  codeBlockBorder: '--code-block-border',
  inlineCodeColor: '--inline-code-color',
  mentionColor: '--mention-color',
  typingIndicatorColor: '--typing-indicator-color',
  scrollButtonBackground: '--scroll-button-background',
  scrollButtonHoverBackground: '--scroll-button-hover-background',
  scrollButtonBorder: '--scroll-button-border',
  scrollButtonIconColor: '--scroll-button-icon-color',
  unreadBadgeBackground: '--unread-badge-background',
  unreadBadgeText: '--unread-badge-text',
  formBackground: '--form-background',
  inputBackground: '--input-background',
  inputText: '--input-text',
  inputPlaceholder: '--input-placeholder',
  sendButtonBackground: '--send-button-background',
  sendButtonText: '--send-button-text',
  sendButtonHoverBackground: '--send-button-hover-background',
  leaveButtonBackground: '--leave-button-background',
  leaveButtonText: '--leave-button-text',
  leaveButtonHoverBackground: '--leave-button-hover-background',
};

function tokenToCssVar(key) {
  return CSS_VAR_MAP[key] || `--${key.replace(/([A-Z])/g, '-$1').toLowerCase()}`;
}

function getAllTokenKeys() {
  return TOKEN_GROUPS.flatMap((group) => group.tokens.map((token) => token.key));
}

function buildExportJson(tokens, presetBase = 'deep-purple') {
  return {
    schemaVersion: 1,
    source: 'chat-color-lab',
    presetBase,
    reference: REFERENCE_URL,
    generatedAt: new Date().toISOString(),
    tokenCount: getAllTokenKeys().length,
    groups: TOKEN_GROUPS.map((group) => group.id),
    tokens: { ...tokens },
  };
}
